/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pmriachodoce.SistemaRiachoDoce.apresentacao;

import br.com.pmriachodoce.SistemaRiachoDoce.entidade.Fornecedor;
import br.com.pmriachodoce.SistemaRiachoDoce.entidade.Produto;
import br.com.pmriachodoce.SistemaRiachoDoce.excecoes.CamposVaziosException;
import br.com.pmriachodoce.SistemaRiachoDoce.excecoes.DescricaoDuplicadaProdutoException;
import br.com.pmriachodoce.SistemaRiachoDoce.excecoes.QuantidadeProdutoInvalidaException;
import br.com.pmriachodoce.SistemaRiachoDoce.excecoes.ValorProdutoInvalidoException;
import br.com.pmriachodoce.SistemaRiachoDoce.negocio.FornecedorBO;
import br.com.pmriachodoce.SistemaRiachoDoce.negocio.ProdutoBO;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Késia Correia
 */
public class CadastroProduto extends javax.swing.JFrame {
    Produto produto;
    private GerenciamentoFornecedor telaGerenciamentoFornecedor = null;
    
    /**
     * Creates new form CadastroProduto
     */
    
    Fornecedor fornecedor = null;
    public CadastroProduto() {
        initComponents();
        this.produto = new Produto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPCadastroProdutos = new javax.swing.JPanel();
        lglFotoProduto = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblUnidade = new javax.swing.JLabel();
        lblQuantidadeEstoque = new javax.swing.JLabel();
        lblValorAtual = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        BtnCadastrar = new javax.swing.JButton();
        BtnLimparTela = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        txtUnidade = new javax.swing.JTextField();
        txtQuantidadeEstoque = new javax.swing.JTextField();
        txtValor = new javax.swing.JFormattedTextField();
        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtQuantidadeMinima = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        lblFornecedorConsulta = new javax.swing.JLabel();
        lblNomeFornecedor = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPCadastroProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblUnidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUnidade.setText("Unidade:");

        lblQuantidadeEstoque.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantidadeEstoque.setText("Quantidade Estoque:");

        lblValorAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorAtual.setText("Valor Atual:");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição:");

        BtnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/botão_cadastrar.png"))); // NOI18N
        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        BtnLimparTela.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnLimparTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/botão_limpar_tela.png"))); // NOI18N
        BtnLimparTela.setText("Limpar Tela");
        BtnLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparTelaActionPerformed(evt);
            }
        });

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/botão_cancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quantidade Mínima:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fonrecedor (CNPJ):");

        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/pesquisar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        lblNomeFornecedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNomeFornecedor.setText("Nome:");

        javax.swing.GroupLayout JPCadastroProdutosLayout = new javax.swing.GroupLayout(JPCadastroProdutos);
        JPCadastroProdutos.setLayout(JPCadastroProdutosLayout);
        JPCadastroProdutosLayout.setHorizontalGroup(
            JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(lblQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                                .addComponent(lblNomeFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFornecedorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorAtual)
                            .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                                .addComponent(BtnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(BtnLimparTela)
                                .addGap(18, 18, 18)
                                .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(2, 2, 2)
                                .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar))
                            .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome)))
                        .addGap(0, 0, 0)
                        .addComponent(lglFotoProduto)
                        .addGap(22, 22, 22))))
        );
        JPCadastroProdutosLayout.setVerticalGroup(
            JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lglFotoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                        .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFornecedorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor))
                        .addGap(8, 8, 8)
                        .addComponent(lblUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPCadastroProdutosLayout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuantidadeEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(lblValorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(txtQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPCadastroProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCadastrar)
                    .addComponent(BtnLimparTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPCadastroProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPCadastroProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lerDadosTela(){
        String descricao = txtDescricao.getText().trim();
        String nome = txtNome.getText().trim();
        String strQuantidadeEstoque = txtQuantidadeEstoque.getText().trim();
        String strValor = txtValor.getText().trim();
        String strQuantidadeMinima = txtQuantidadeMinima.getText().trim();
        
        String mensagem = "";
        
        if(descricao.isEmpty()){
            mensagem = "Campo descricao é obrigatório.";
        }
        
        int quantidade = 0;
        if(strQuantidadeEstoque.isEmpty()){
            mensagem = mensagem + "\nCampo Quantidade é obrigatório.";
        }else{
            try{
                quantidade = Integer.parseInt(strQuantidadeEstoque);
            } catch(NumberFormatException nfe){
                mensagem = mensagem + "\nQuantidade Invalida.";
            }
        }
        
        double valorUnitario = 0;
        if(strValor.isEmpty()){
            mensagem = mensagem + "\nCampo Valor Unitário é obrigatório.";
        }else{
            try {
                DecimalFormat formatador = new DecimalFormat("#,##0.00");
                valorUnitario = formatador.parse(strValor).doubleValue();
            } catch (ParseException ex) {
                mensagem = mensagem + "\nValor Unitário Invalido";
            }
        }
        
        int quantidadeMinima = 0;
        if(!strQuantidadeMinima.isEmpty()){
            try{
                quantidadeMinima = Integer.parseInt(strQuantidadeMinima);
            } catch(NumberFormatException nfe){
                mensagem = mensagem + "\nQuantidade Minima Invalida.";
            }
        }
        
        if(mensagem == "" || mensagem == null){
            produto.setDescricao(descricao);
            produto.setNome(nome);
            produto.setQuantidadeEstoque(quantidade);
            produto.setQuantidadeMinima(quantidadeMinima);
            produto.setValorUnitario(valorUnitario);
        }else{
            throw new CamposVaziosException(mensagem);
        }
    }
    
    private void exibirMensagemErro(String mensagem, String titulo) {
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        }

     private void exibirMensagemSucesso(String mensagem, String titulo) {
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        try{
            lerDadosTela();
            ProdutoBO produtoBO = new ProdutoBO();
            produtoBO.criar(produto);
            exibirMensagemSucesso( "Produto cadastro com sucesso\n Codigo cadastrado : " + produto.getCodigo(), "Cadastrar produto");
        } catch(CamposVaziosException cve){
            exibirMensagemErro(cve.getMessage(), "Cadastrar produto");
        } catch(DescricaoDuplicadaProdutoException pdde){
            exibirMensagemErro(pdde.getMessage(),  "Cadastrar produto");
        }catch(QuantidadeProdutoInvalidaException qpie){
            exibirMensagemErro (qpie.getMessage(),  "Cadastrar produto");
        }catch(ValorProdutoInvalidoException vpie){
           exibirMensagemErro(vpie.getMessage(),  "Cadastrar produto");
        }catch(SQLException se){
            exibirMensagemErro("Erro desconhecido. Contate com o adminstrador do sistema",  "Cadastrar produto");
        }
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    private void BtnLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparTelaActionPerformed
        lblNome.setText("");
        txtUnidade.setText("");
        txtCNPJ.setText("");
        txtQuantidadeEstoque.setText("");
        txtQuantidadeMinima.setText("");
        txtDescricao.setText("");
        txtValor.setText("");
        lblNome.requestFocus();
    }//GEN-LAST:event_BtnLimparTelaActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private String lerCNPJ() {
        String CNPJ = txtCNPJ.getText().trim();

        String mensagem = "";

        if (CNPJ.length() < 14) {
            mensagem = "CNPJ inválido.";
        }

        if (!(mensagem == "" || mensagem == null)) {
            throw new CamposVaziosException(mensagem);
        }

        return CNPJ;
    }
    
    private void setNomeFornecedorTela() {
        lblNomeFornecedor.setVisible(true);
        lblNomeFornecedor.setText(fornecedor.getNome());
        lblNomeFornecedor.setVisible(true);
    }
    
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
           FornecedorBO fornecedorBO = new FornecedorBO();
            fornecedor = fornecedorBO.buscarCNPJ(lerCNPJ());   
            this.setNomeFornecedorTela();
        }catch(SQLException e){
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de Compra", JOptionPane.ERROR_MESSAGE); 
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnLimparTela;
    private javax.swing.JPanel JPCadastroProdutos;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblFornecedorConsulta;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblQuantidadeEstoque;
    private javax.swing.JLabel lblUnidade;
    private javax.swing.JLabel lblValorAtual;
    private javax.swing.JLabel lglFotoProduto;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQuantidadeEstoque;
    private javax.swing.JTextField txtQuantidadeMinima;
    private javax.swing.JTextField txtUnidade;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
