/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pmriachodoce.SistemaRiachoDoce.apresentacao;

import br.com.pmriachodoce.SistemaRiachoDoce.entidade.Produto;
import br.com.pmriachodoce.SistemaRiachoDoce.negocio.ProdutoBO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Késia Correia
 */
public class GerenciamentoProduto extends javax.swing.JFrame {

    List<Produto> produtos = new ArrayList<>();
    MenuPrincipal menuPrincipal = null;
    /**
     * Creates new form GerenciamentoProduto
     */
    public GerenciamentoProduto() {
        initComponents();
    }
    
     public GerenciamentoProduto(MenuPrincipal menuPrincipal) {
        initComponents();  
        buscarTodosProduto();
        this.menuPrincipal = menuPrincipal;
    }
     
     public void buscarTodosProduto(){
        
        try{         
            ProdutoBO produtoBO = new ProdutoBO();
            produtos = produtoBO.buscarTodos();
            carregarDadosTabela();
        }catch(Exception e){
            exibirMensagemErro( "Erro desconhecido. Contate com administrador", "Consultar Produto");
        }
    }
    
    public void carregarDadosTabela(){
        Model modelo = new GerenciamentoProduto.Model();
        this.tbProduto.setModel(modelo);
    }
    
    private void exibirMensagemErro(String mensagem, String titulo) {
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        }

        private void exibirMensagemSucesso(String mensagem, String titulo) {
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
        }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscaProdutos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        lblNomeProduto = new javax.swing.JLabel();
        lblFotoProduto = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento: Produtos");

        jPanelBuscaProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relação de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbProduto);

        lblNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanelBuscaProdutosLayout = new javax.swing.GroupLayout(jPanelBuscaProdutos);
        jPanelBuscaProdutos.setLayout(jPanelBuscaProdutosLayout);
        jPanelBuscaProdutosLayout.setHorizontalGroup(
            jPanelBuscaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscaProdutosLayout.createSequentialGroup()
                .addGroup(jPanelBuscaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscaProdutosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblNomeProduto))
                    .addGroup(jPanelBuscaProdutosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lblFotoProduto)
                .addContainerGap())
        );
        jPanelBuscaProdutosLayout.setVerticalGroup(
            jPanelBuscaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscaProdutosLayout.createSequentialGroup()
                .addGroup(jPanelBuscaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBuscaProdutosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFotoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BtnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/botão_Editar2.jpg"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/Botão_Excluir.jpg"))); // NOI18N
        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145)
                        .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelBuscaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelBuscaProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutoMouseClicked
        
    }//GEN-LAST:event_tbProdutoMouseClicked

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        int linhaSelecionada = this.tbProduto.getSelectedRow();
        
        if(linhaSelecionada != -1){
                 Produto produtoSelecionado = this.produtos.get(linhaSelecionada);
                 EdicaoProduto telaEditarDadosProduto = new EdicaoProduto(this, produtoSelecionado);
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.tbProduto.getSelectedRow();
        if(linhaSelecionada != -1){
            Produto produtoSelecionado = this.produtos.get(linhaSelecionada);

            int resposta;
            String mensagem = "Deseja excluir produto " + produtoSelecionado.getNome() + " ?";
            String titulo = "Excluir produto";
            resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    ProdutoBO produtoBO = new ProdutoBO();
                    produtoBO.excluirProduto(produtoSelecionado);
                    this.buscarTodosProduto();
                    exibirMensagemSucesso("Dados excluidos com sucesso!", "Excluir cliente");                
                } catch (Exception e) {
                    mensagem = "Erro desconhecido. Entre em contato com o administrador do sistema.";
                    exibirMensagemErro(mensagem, "Excluir cliente");
                }
            }else{
                exibirMensagemSucesso("Dados não excluidos", "Excluir cliente");
            }
        }else{
          String mensagem = "Nenhum cliente selecionado.";
          JOptionPane.showMessageDialog(this, mensagem, "Excluir produto", JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JPanel jPanelBuscaProdutos;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFotoProduto;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JTable tbProduto;
    // End of variables declaration//GEN-END:variables

public class Model extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return produtos.size();
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int linha, int coluna) {
          Produto produto = produtos.get(linha);
            if(coluna == 0){
                return produto.getNome();
            }else if(coluna == 1){
                return produto.getValorUnitario();
            }else if(coluna == 2){
               return produto.getDescricao();
            }else if(coluna == 3){
                return produto.getQuantidadeEstoque();
            }else if(coluna == 4){
                return produto.getDescricao();
            }else if(coluna == 5){
                return produto.getUnidade();
            }
            return null;
        }
        
        @Override
        public String getColumnName(int coluna){
            if(coluna == 0){
                return "NOME";
            }else if(coluna == 1){
                return "VALOR_UNITARIO";
            }else if(coluna == 2){
               return "DESCRIÇÃO"; 
            }else if(coluna == 3){
                return "QUANTIDADE_ESTOQUE";
            }else if(coluna == 4){
                return "DESCRIÇÃO";
            }else if(coluna == 5){
                return "UNIDADE";
            }
            return null;
    }
}
}
