/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pmriachodoce.SistemaRiachoDoce.apresentacao;

import br.com.pmriachodoce.SistemaRiachoDoce.entidade.Fornecedor;
import br.com.pmriachodoce.SistemaRiachoDoce.negocio.FornecedorBO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Késia Correia
 */
public class GerenciamentoFornecedor extends javax.swing.JFrame {
    List<Fornecedor> fornecedores = new ArrayList<>();
    MenuPrincipal menuPrincipal = null;
    /**
     * Creates new form GerenciamentoFornecedor
     */
    public GerenciamentoFornecedor() {
        initComponents();
    }
    
    public GerenciamentoFornecedor(MenuPrincipal menuPrincipal) {
        initComponents();  
        buscarTodosFornecedor();
        this.menuPrincipal = menuPrincipal;
    }
    
    public void buscarTodosFornecedor(){
        
        try{         
            FornecedorBO fornecedorBO = new FornecedorBO();
            fornecedores = fornecedorBO.buscarTodos();
            carregarDadosTabela();
        }catch(Exception e){
            exibirMensagemErro( "Erro desconhecido. Contate com administrador", "Consultar Cliente");
        }
    }
    
    public void carregarDadosTabela(){
        Model modelo = new GerenciamentoFornecedor.Model();
        this.tbFornecedor.setModel(modelo);
    }
    
    private void exibirMensagemErro(String mensagem, String titulo) {
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
        }

    private void exibirMensagemSucesso(String mensagem, String titulo) {
            JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBuscaFornecedores = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbFornecedor = new javax.swing.JTable();
        lblFotoFornec = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBuscaFornecedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relação de Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tbFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFornecedorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbFornecedor);

        javax.swing.GroupLayout jPanelBuscaFornecedoresLayout = new javax.swing.GroupLayout(jPanelBuscaFornecedores);
        jPanelBuscaFornecedores.setLayout(jPanelBuscaFornecedoresLayout);
        jPanelBuscaFornecedoresLayout.setHorizontalGroup(
            jPanelBuscaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscaFornecedoresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFotoFornec)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanelBuscaFornecedoresLayout.setVerticalGroup(
            jPanelBuscaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscaFornecedoresLayout.createSequentialGroup()
                .addGroup(jPanelBuscaFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFotoFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBuscaFornecedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BtnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/botão_Editar2.jpg"))); // NOI18N
        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/Botão_Excluir.jpg"))); // NOI18N
        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelBuscaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanelBuscaFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFornecedorMouseClicked
 
    }//GEN-LAST:event_tbFornecedorMouseClicked

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.tbFornecedor.getSelectedRow();
        if(linhaSelecionada != -1){
                 Fornecedor fornecedorSelecionado = this.fornecedores.get(linhaSelecionada);  
                 EdicaoFornecedor telaEditarDadosFornecedor = new EdicaoFornecedor(this, fornecedorSelecionado);
        }
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.tbFornecedor.getSelectedRow();
        if(linhaSelecionada != -1){
           Fornecedor fornecedorSelecionado = this.fornecedores.get(linhaSelecionada);

            int resposta;
            String mensagem = "Deseja excluir fornecedor " + fornecedorSelecionado.getNome() + " ?";
            String titulo = "Excluir fornecedor";
            resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    FornecedorBO fornecedorBO = new FornecedorBO();
                    fornecedorBO.deletarFornecedor(fornecedorSelecionado);
                    this.buscarTodosFornecedor();
                    exibirMensagemSucesso("Dados excluidos com sucesso!", "Excluir fornecedor");                
                } catch (Exception e) {
                    mensagem = "Erro desconhecido. Entre em contato com o administrador do sistema.";
                    exibirMensagemErro(mensagem, "Excluir fornecedor");
                }
            }else{
                exibirMensagemSucesso("Dados não excluidos", "Excluir fornecedor");
            }
        }else{
          String mensagem = "Nenhum fornecedor selecionado.";
          JOptionPane.showMessageDialog(this, mensagem, "Excluir fornecedor", JOptionPane.INFORMATION_MESSAGE);  
        }
    }//GEN-LAST:event_BtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JPanel jPanelBuscaFornecedores;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFotoFornec;
    private javax.swing.JTable tbFornecedor;
    // End of variables declaration//GEN-END:variables

    public class Model extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return fornecedores.size();
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int linha, int coluna) {
           Fornecedor fornecedor = fornecedores.get(linha);
            if(coluna == 0){
                return fornecedor.getCNPJ();
            }else if(coluna == 1){
                return fornecedor.getDescricao();
            }else if(coluna == 2){
               return fornecedor.getNome();
            }else if(coluna == 3){
                return fornecedor.getTelefone();
            }else if(coluna == 4){
                return fornecedor.getEndereco();
            }
            return null;
        }
        
        @Override
        public String getColumnName(int coluna){
            if(coluna == 0){
                return "CNPJ";
            }else if(coluna == 1){
                return "Descricao";
            }else if(coluna == 2){
               return "Nome"; 
            }else if(coluna == 3){
                return "Telefone";
            }else if(coluna == 4){
                return "Endereço";
            }
            return null;
    }
}
}
