package br.com.pmriachodoce.SistemaRiachoDoce.apresentacao;


import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.CadastroCliente;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.CadastroCompra;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.CadastroFornecedor;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.CadastroProduto;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.CadastroUsuarios;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.GerenciamentoCliente;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.GerenciamentoCompra;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.GerenciamentoComprasRealizadas;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.GerenciamentoFornecedor;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.GerenciamentoFuncionario;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.GerenciamentoProduto;
import br.com.pmriachodoce.SistemaRiachoDoce.apresentacao.MenuPrincipal;
import br.com.pmriachodoce.SistemaRiachoDoce.entidade.Fornecedor;
import br.com.pmriachodoce.SistemaRiachoDoce.entidade.GraficoVendas;
import br.com.pmriachodoce.SistemaRiachoDoce.entidade.Usuario;
import br.com.pmriachodoce.SistemaRiachoDoce.excecoes.InvalidoException;
import br.com.pmriachodoce.SistemaRiachoDoce.negocio.ComprasRealizadasClientesBO;
import br.com.pmriachodoce.SistemaRiachoDoce.negocio.FornecedorBO;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Késia Correia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private CadastroCliente telaCadCliente = null;
    private CadastroUsuarios telaCadUsuario = null;
    private GerenciamentoFuncionario telaConsultaUsuario = null;
    private GerenciamentoCliente telaConsultaCliente = null;
    private CadastroProduto telaCadProduto = null;
    private GerenciamentoProduto telaConsultaProduto = null;
    private GerenciamentoComprasRealizadas telaConsultaComprasRealizadas = null;
    private CadastroCompra telaCompra = null;
    
    Usuario usuario = null;
   
    public MenuPrincipal(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }
    /**
     * Creates new form MenuPrincipau
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        JmCadastros = new javax.swing.JMenu();
        jMCadastrosFuncionarios = new javax.swing.JMenuItem();
        jMCadastrosClientes = new javax.swing.JMenuItem();
        jMCadastrosFornecedor = new javax.swing.JMenuItem();
        JmGCadastros = new javax.swing.JMenu();
        JMGestaoFuncionarios = new javax.swing.JMenuItem();
        JMGestaoClientes = new javax.swing.JMenuItem();
        JMGestaoFornecedores = new javax.swing.JMenuItem();
        JmVendas = new javax.swing.JMenu();
        JMenuCadastroCompra = new javax.swing.JMenuItem();
        JMenuGerenciadorCompra = new javax.swing.JMenuItem();
        JmRelatorios = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        JmenuRelatorioFornecedores = new javax.swing.JMenuItem();
        JMGráficos = new javax.swing.JMenu();
        jMenuGraficoVendas = new javax.swing.JMenuItem();
        jmEstoque = new javax.swing.JMenu();
        jMCadastrosProduto = new javax.swing.JMenuItem();
        JMGestaoProdutos = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu: Padaria & Mercearia Riacho Doce");

        JmCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/Cadastrar.jpg"))); // NOI18N
        JmCadastros.setText("Cadastros");

        jMCadastrosFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_MASK));
        jMCadastrosFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/usuário_menor.jpg"))); // NOI18N
        jMCadastrosFuncionarios.setText("Funcionários");
        jMCadastrosFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrosFuncionariosActionPerformed(evt);
            }
        });
        JmCadastros.add(jMCadastrosFuncionarios);

        jMCadastrosClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_MASK));
        jMCadastrosClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/func.png"))); // NOI18N
        jMCadastrosClientes.setText("Clientes");
        jMCadastrosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrosClientesActionPerformed(evt);
            }
        });
        JmCadastros.add(jMCadastrosClientes);

        jMCadastrosFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        jMCadastrosFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/fornecedor.png"))); // NOI18N
        jMCadastrosFornecedor.setText("Fornecedores");
        jMCadastrosFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrosFornecedorActionPerformed(evt);
            }
        });
        JmCadastros.add(jMCadastrosFornecedor);

        jMenuBar2.add(JmCadastros);

        JmGCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/Gestão.png"))); // NOI18N
        JmGCadastros.setText("Gestão de Cadastros");

        JMGestaoFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        JMGestaoFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/usuário_menor.jpg"))); // NOI18N
        JMGestaoFuncionarios.setText("Funcionários");
        JMGestaoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGestaoFuncionariosActionPerformed(evt);
            }
        });
        JmGCadastros.add(JMGestaoFuncionarios);

        JMGestaoClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        JMGestaoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/func.png"))); // NOI18N
        JMGestaoClientes.setText("Clientes");
        JMGestaoClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGestaoClientesActionPerformed(evt);
            }
        });
        JmGCadastros.add(JMGestaoClientes);

        JMGestaoFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        JMGestaoFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/fornecedor.png"))); // NOI18N
        JMGestaoFornecedores.setText("Fornecedores");
        JMGestaoFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGestaoFornecedoresActionPerformed(evt);
            }
        });
        JmGCadastros.add(JMGestaoFornecedores);

        jMenuBar2.add(JmGCadastros);

        JmVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/venda.png"))); // NOI18N
        JmVendas.setText("Gestão de  Compras");

        JMenuCadastroCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_MASK));
        JMenuCadastroCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/compra2.png"))); // NOI18N
        JMenuCadastroCompra.setText("Cadastrar Compra");
        JMenuCadastroCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuCadastroCompraActionPerformed(evt);
            }
        });
        JmVendas.add(JMenuCadastroCompra);

        JMenuGerenciadorCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_MASK));
        JMenuGerenciadorCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/editarcompra.png"))); // NOI18N
        JMenuGerenciadorCompra.setText("Gerenciamento das Compras");
        JMenuGerenciadorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuGerenciadorCompraActionPerformed(evt);
            }
        });
        JmVendas.add(JMenuGerenciadorCompra);

        jMenuBar2.add(JmVendas);

        JmRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/relatorio-social-media.jpg"))); // NOI18N
        JmRelatorios.setText("Relatórios");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/relatorio.png"))); // NOI18N
        jMenuItem8.setText("Cliente em Débito");
        JmRelatorios.add(jMenuItem8);

        JmenuRelatorioFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        JmenuRelatorioFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/report_user.png"))); // NOI18N
        JmenuRelatorioFornecedores.setText("Fornecedores");
        JmenuRelatorioFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmenuRelatorioFornecedoresActionPerformed(evt);
            }
        });
        JmRelatorios.add(JmenuRelatorioFornecedores);

        jMenuBar2.add(JmRelatorios);

        JMGráficos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/report2.png"))); // NOI18N
        JMGráficos.setText("Gráficos");

        jMenuGraficoVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuGraficoVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/gráfico_vendas.png"))); // NOI18N
        jMenuGraficoVendas.setText("Gráfico das Vendas");
        jMenuGraficoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGraficoVendasActionPerformed(evt);
            }
        });
        JMGráficos.add(jMenuGraficoVendas);

        jMenuBar2.add(JMGráficos);

        jmEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/estoque.png"))); // NOI18N
        jmEstoque.setText("Estoque");

        jMCadastrosProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jMCadastrosProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/produtos.png"))); // NOI18N
        jMCadastrosProduto.setText("Cadastro Produtos");
        jMCadastrosProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrosProdutoActionPerformed(evt);
            }
        });
        jmEstoque.add(jMCadastrosProduto);

        JMGestaoProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        JMGestaoProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pmriachodoce/SistemaRiachoDoce/apresentacao/icones/produtos.png"))); // NOI18N
        JMGestaoProdutos.setText("Gerenciamento Produtos");
        JMGestaoProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMGestaoProdutosActionPerformed(evt);
            }
        });
        jmEstoque.add(JMGestaoProdutos);

        jMenuBar2.add(jmEstoque);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuCadastroCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuCadastroCompraActionPerformed
        CadastroCompra cadasdtroCompra = new  CadastroCompra(usuario);
        cadasdtroCompra.setVisible(true);
    }//GEN-LAST:event_JMenuCadastroCompraActionPerformed

    private void JMenuGerenciadorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuGerenciadorCompraActionPerformed
        GerenciamentoCompra gerenciamentoCompra = new  GerenciamentoCompra ();
        gerenciamentoCompra.setVisible(true);
    }//GEN-LAST:event_JMenuGerenciadorCompraActionPerformed

    private void JmenuRelatorioFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmenuRelatorioFornecedoresActionPerformed
        List<Fornecedor>fornecedor = null;
        try {
            FornecedorBO fornecedorBO = new FornecedorBO();
            fornecedor = fornecedorBO.buscarTodos();
            this.gerarPdfFornecedor(fornecedor);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro desconhecido. Contate com adminstrador", "Consultar produtos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_JmenuRelatorioFornecedoresActionPerformed

    private void jMenuGraficoVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGraficoVendasActionPerformed
        try {
            // TODO add your handling code here:
            ComprasRealizadasClientesBO comprasRealizadasClienteBO = new ComprasRealizadasClientesBO();
            List<GraficoVendas> vendasMensais = comprasRealizadasClienteBO.buscarPorMes();
            this.gerarGraficoVendasMensais(vendasMensais);
        }catch (InvalidoException aie) {
            JOptionPane.showMessageDialog(this,aie.getMessage(), "Consultar vendas", JOptionPane.ERROR_MESSAGE);
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro desconhecido. Contate com adminstrador", "Consultar vendas", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuGraficoVendasActionPerformed

    public void gerarPdfFornecedor(List<Fornecedor> fornecedor){
         try{ 
            String arquivoRelatorio = System.getProperty("user.dir")
                   + "/relatorios/RelatorioFornecedor.jasper";
            
            Map<String, Object> paramentros = new HashMap<String, Object>();
            
            JRBeanCollectionDataSource fonteDados 
                      = new JRBeanCollectionDataSource(fornecedor);
            
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, paramentros, fonteDados);
            
            JasperViewer telaExibicaoRelatorio 
                       = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Relatório de Fornecedores");
            telaExibicaoRelatorio.setVisible(true);
        } catch(JRException ex){            
            JOptionPane.showMessageDialog(this, "Erro ao exibir relatório.", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    public void gerarGraficoVendasMensais( List<GraficoVendas> vendasMensais){
        try{
            String arquivoRelatorio = System.getProperty("user.dir")
                   + "/relatorios/GraficoVendasMensal.jasper";
            
            Map<String, Object> paramentros = new HashMap<String, Object>();
            
            JRBeanCollectionDataSource fonteDados 
                      = new JRBeanCollectionDataSource(vendasMensais);
            
            JasperPrint relatorioGerado = JasperFillManager.fillReport(arquivoRelatorio, paramentros, fonteDados);
            
            JasperViewer telaExibicaoRelatorio 
                       = new JasperViewer(relatorioGerado, false);
            telaExibicaoRelatorio.setTitle("Gráfico: Vendas Mensais");
            telaExibicaoRelatorio.setVisible(true);
        } catch(JRException ex){            
            JOptionPane.showMessageDialog(this, "Erro ao exibir gráfico de vendas mensais.", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    private void jMCadastrosProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrosProdutoActionPerformed
        // TODO add your handling code here:
        CadastroProduto cadastroProduto = new CadastroProduto();
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_jMCadastrosProdutoActionPerformed

    private void JMGestaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGestaoProdutosActionPerformed
        GerenciamentoProduto gerenciamentoProduto = new  GerenciamentoProduto();
        gerenciamentoProduto.setVisible(true);
    }//GEN-LAST:event_JMGestaoProdutosActionPerformed

    private void JMGestaoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGestaoFuncionariosActionPerformed
        GerenciamentoFuncionario gerenciamentoFuncionario = new  GerenciamentoFuncionario();
        gerenciamentoFuncionario.setVisible(true);
    }//GEN-LAST:event_JMGestaoFuncionariosActionPerformed

    private void JMGestaoClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGestaoClientesActionPerformed
        GerenciamentoCliente gerenciamentoCliente = new  GerenciamentoCliente();
        gerenciamentoCliente.setVisible(true);
    }//GEN-LAST:event_JMGestaoClientesActionPerformed

    private void JMGestaoFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMGestaoFornecedoresActionPerformed
        // TODO add your handling code here:
        GerenciamentoFornecedor gerenciamentoFornecedor = new  GerenciamentoFornecedor();
        gerenciamentoFornecedor.setVisible(true);
    }//GEN-LAST:event_JMGestaoFornecedoresActionPerformed

    private void jMCadastrosFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrosFuncionariosActionPerformed
        CadastroUsuarios cadastroUsuarios = new CadastroUsuarios();
        cadastroUsuarios.setVisible(true);
    }//GEN-LAST:event_jMCadastrosFuncionariosActionPerformed

    private void jMCadastrosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrosClientesActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_jMCadastrosClientesActionPerformed

    private void jMCadastrosFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrosFornecedorActionPerformed
        // TODO add your handling code here:
        CadastroFornecedor cadastroFornecedor = new CadastroFornecedor();
        cadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_jMCadastrosFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMGestaoClientes;
    private javax.swing.JMenuItem JMGestaoFornecedores;
    private javax.swing.JMenuItem JMGestaoFuncionarios;
    private javax.swing.JMenuItem JMGestaoProdutos;
    private javax.swing.JMenu JMGráficos;
    private javax.swing.JMenuItem JMenuCadastroCompra;
    private javax.swing.JMenuItem JMenuGerenciadorCompra;
    private javax.swing.JMenu JmCadastros;
    private javax.swing.JMenu JmGCadastros;
    private javax.swing.JMenu JmRelatorios;
    private javax.swing.JMenu JmVendas;
    private javax.swing.JMenuItem JmenuRelatorioFornecedores;
    private javax.swing.JMenuItem jMCadastrosClientes;
    private javax.swing.JMenuItem jMCadastrosFornecedor;
    private javax.swing.JMenuItem jMCadastrosFuncionarios;
    private javax.swing.JMenuItem jMCadastrosProduto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuGraficoVendas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu jmEstoque;
    // End of variables declaration//GEN-END:variables
}
